language: ruby
rvm:
  - "2.3.0"
before_script:
  - mysql -e 'create database theoj_test;'
  - bundle install
  - bundle exec rake db:schema:load

notifications:
  email:
    - arfon.smith@gmail.com
    - marc@marcrohloff.com
    - stuart.lynn@gmail.com

script: bundle exec rspec
